# Generated by Django 5.2 on 2025-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="note",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="note",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="note",
            name="original_filename",
        ),
        migrations.AddField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notes/"),
        ),
    ]
