# Generated by Django 5.2 on 2025-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_note_file_path_remove_note_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
